### ISSUE TITLE
cannot run pip install GetOldTweets3

### ISSUE THREAD

**Issue by humasak** [Mottl/GetOldTweets3#7]
Hi,
I tried to execute "pip install GetOldTweets3" in linux server. But it is not successfull and i got this message:
```
Could not find a version that satisfies the requirement GetOldTweets3 (from versions: )
No matching distribution found for GetOldTweets3
```
need help to solve this. thank you.

**Comment by Mottl** [comment]
You need version 3.4+ of Python. Which version of Python do you use?

**Comment by rafaeloliveiras** [comment]
Hi @Mottl  how are you?  Hope you fine! 
What is the steps to get it installed? 
I cloned the Jefferson's GetOldTweets project to my folder.. So now may I should put GetOldTweets3 inside that folder?

Because if I run "pip3 install GetOldTweets3" it will be installed. But if i put in the terminal "GetOldTweets3 -h" the answer is: Command not found

There's some way to clean a Tweet with "@RT" or links, news ?

Thank you!

**Comment by Mottl** [comment]
> What is the steps to get it installed?

```pip install GetOldTweets3```

> I cloned the Jefferson's GetOldTweets project to my folder.. So now may I should put GetOldTweets3 inside that folder?

No, don't mix them.

> Because if I run "pip3 install GetOldTweets3" it will be installed. But if i put in the terminal "GetOldTweets3 -h" the answer is: Command not found

In which folder does `pip` install packages on your system?

> There's some way to clean a Tweet with "@rt" or links, news ?

You can download tweets with GetOldTweets3 utility as-is to csv file and then preprocess it with your favorite tool (python, sed, perl, vim).
